AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  myDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "pet_species"
          AttributeType: "S"
        - 
          AttributeName: "pet_id"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "pet_species"
          KeyType: "HASH"
        - 
          AttributeName: "pet_id"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "PetInventory"
      